### ISSUE TITLE
For Xcode 10.2.1 with swift version 4.2

### ISSUE THREAD

**Issue by jayarajm** [geouniq/GeoUniqSDK-iOS-Swift-5#1]
Which version of GeoUniqSDk I need to use. 
I'm getting error while using all SDK version below
Module compiled with Swift 5.1 cannot be imported by the Swift 5.0.1 compiler: ***/Pods/GeoUniq-Swift5/GeoUniq.framework/Modules/GeoUniq.swiftmodule/i386.swiftmodule

Please help me to resolve it.

**Comment by paologeouniq** [comment]
For compatibility check [documentation](https://gitlab.com/geouniq/documentation/-/blob/master/sdk/integration/ios.md#reference-versions)
