### ISSUE TITLE
Api for geouniq async device ID

### ISSUE THREAD

**Issue by aiKrice** [geouniq/GeoUniqSDK-iOS-Swift-5#2]
Actually in documentation i can't see how to fetch the device id in asynchronous way in opposite of Android.
Does this method exist ?
@paolodonato

**Comment by paologeouniq** [comment]
Hi @SaezChristopher ,
sorry for delay.

The method is:

>        let _ = GeoUniq.sharedInstance { (deviceId) in
>             // Use here deviceId
>         }
		
Good job
