### ISSUE TITLE
SessionDelegate class conflicts with Alamofire

### ISSUE THREAD

**Issue by soucolline** [geouniq/GeoUniqSDK-iOS-Swift-5#3]
Hi, I've got a conflict when trying to import GeoUniq as the class `SessionDelegate` already exists in Alamofire : 

```
SessionDelegate' has different definitions in different modules; first difference is definition in module 'Alamofire.Swift' found method with no designater initializer
```

This problem already appeared in multiple projects, for example KingFisher had to rename the class to prefix it : https://github.com/onevcat/Kingfisher/releases/tag/5.15.4

Could you rename the `SessionDelegate` class to avoid clashing with Alamofire ?

Thanks

**Comment by paologeouniq** [comment]
fixed
